"""add user role

Revision ID: 6406e9a2dfc3
Revises: 
Create Date: 2026-09-07 03:53:44.660006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6406e9a2dfc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False, server_default = '1'))
    op.alter_column('orders', 'satus', new_column_name='status')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default = 'customer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column(
        'orders',
        'status',
        new_column_name='satus'
    )
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###
